# Generated by Django 4.2.20 on 2025-10-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
