# Generated by Django 4.2.20 on 2025-10-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registration_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
